drop table import_tracks;

create table import_tracks(
  id            number
    generated by default as identity
  , node_from     varchar2( 20 char )
  , node_to       varchar2( 20 char )
  , track_length  integer
);
/

drop table versioned_tracks;

create table versioned_tracks(
  id            number
    generated by default as identity
  , node_from     varchar2( 20 char )
  , node_to       varchar2( 20 char )
  , track_length  integer
  , valid_from    date
  , valid_until   date
  , track_comment varchar2( 4000 char )
);

-- recompile invalid packages
begin
  for cur in(
    select object_name
         , object_type        
    from user_objects
    where object_type in( 'PACKAGE'
                        , 'PACKAGE BODY' )          
          and status = 'INVALID'
          order by object_type
  )loop
    begin
      if cur.object_type = 'PACKAGE BODY' then
        execute immediate 'alter package '
                          || cur.object_name
                          || ' compile body';
      else
        execute immediate 'alter '
                          || cur.object_type
                          || ' '
                          || cur.object_name
                          || ' compile';
      end if;

    exception
      when others then
        null;
    end;
  end loop;
end;
/